services:
  app:
    build: .
    image: mcp-maax-cob:latest
    environment:
      - NODE_ENV=production
      - MCP_TRANSPORT=hybrid
      - MCP_HTTP_PORT=4004
      - MCP_WS_PORT=4005
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - MCP_TOKEN_SECRET=${MCP_TOKEN_SECRET:-dev-maax-cob-secret}
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - ENCRYPTION_KEY_HEX=${ENCRYPTION_KEY_HEX:-0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef}
      - WEBHOOK_HMAC_SECRET=${WEBHOOK_HMAC_SECRET:-mcp-webhook-secret-2025}
      - RATE_LIMIT=120
    ports:
      - "4004:4004"
      - "4005:4005"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
