version: '3.8'

name: mcp-maax-cob-custom

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: mcp
      POSTGRES_USER: mcpuser
      POSTGRES_PASSWORD: mcppass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Porta alternativa para PostgreSQL (5433 ao invés de 5432)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mcpuser -d mcp"]
      interval: 30s
      timeout: 10s
      retries: 5

  # MCP Server (STDIO + HTTP/SSE + WebSocket)
  mcp:
    build:
      context: .
      dockerfile: Dockerfile.mcp
      target: runtime
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      MCP_TRANSPORT: http
      MCP_HTTP_PORT: 4004  # Nova porta HTTP
      MCP_WS_PORT: 4005    # Nova porta WebSocket
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: mcp
      POSTGRES_USER: mcpuser
      POSTGRES_PASSWORD: mcppass
      ENCRYPTION_KEY_HEX: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
      WEBHOOK_HMAC_SECRET: mcp-webhook-secret-2025
      RATE_LIMIT: 120
    ports:
      - "4004:4004"  # HTTP/SSE na porta 4004
      - "4005:4005"  # WebSocket na porta 4005
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4004/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # REST API - COMENTADO (não queremos usar porta 3000 ou 4006)
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   environment:
  #     NODE_ENV: production
  #     PORT: 4006  # REST API na porta 4006
  #     POSTGRES_HOST: db
  #     POSTGRES_PORT: 5432
  #     POSTGRES_DB: mcp
  #     POSTGRES_USER: mcpuser
  #     POSTGRES_PASSWORD: mcppass
  #     ENCRYPTION_KEY_HEX: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
  #     WEBHOOK_HMAC_SECRET: mcp-webhook-secret-2025
  #     RATE_LIMIT: 120
  #   ports:
  #     - "4006:4006"  # REST API na porta 4006
  #   healthcheck:
  #     test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4006/health/ready"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5

volumes:
  postgres_data:

networks:
  default:
    name: mcp-network-custom