version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mcp
      POSTGRES_USER: mcpuser
      POSTGRES_PASSWORD: mcppass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mcpuser -d mcp"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MCP Server
  mcp:
    build:
      context: .
      dockerfile: Dockerfile.mcp-simple
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      MCP_TRANSPORT: http
      MCP_HTTP_PORT: 4004
      MCP_WS_PORT: 4005
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: mcp
      POSTGRES_USER: mcpuser
      POSTGRES_PASSWORD: mcppass
      ENCRYPTION_KEY_HEX: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
      WEBHOOK_HMAC_SECRET: mcp-webhook-secret-2025
      RATE_LIMIT: 120
    ports:
      - "4004:4004"
      - "4005:4005"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4004/health"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: