version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mcp:
    build:
      context: .
      dockerfile: Dockerfile.mcp-simple
    depends_on:
      redis:
        condition: service_healthy
    environment:
      NODE_ENV: production
      MCP_TRANSPORT: http
      MCP_HTTP_PORT: 4004
      MCP_WS_PORT: 4005
      MCP_TOKEN_SECRET: ${MCP_TOKEN_SECRET:-dev-maax-cob-secret-change-in-production}
      REDIS_URL: redis://redis:6379
      ENCRYPTION_KEY_HEX: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
      WEBHOOK_HMAC_SECRET: mcp-webhook-secret-2025
      RATE_LIMIT: 120
    ports:
      - "4004:4004"
      - "4005:4005"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4004/health"]
      interval: 30s
      timeout: 10s
      retries: 5
